import { Artwork } from "@/types";

export const artworks: Artwork[] = [
  // === Gouache Paintings (74) ===
  { title: "物競天擇", titleZh: "物競天擇", slug: "natural-selection", image: "/images/gouache/01-natural-selection.jpg", category: "gouache" },
  { title: "覓食", titleZh: "覓食", slug: "foraging", image: "/images/gouache/02-foraging.jpg", category: "gouache" },
  { title: "合家歡", titleZh: "合家歡", slug: "family-gathering", image: "/images/gouache/03-family-gathering.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-1", image: "/images/gouache/04-untitled-1.jpg", category: "gouache" },
  { title: "花現 非典型膠彩畫", titleZh: "花現 非典型膠彩畫", slug: "flower-discovery", image: "/images/gouache/05-flower-discovery.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-2", image: "/images/gouache/06-untitled-2.jpg", category: "gouache" },
  { title: "心之嚮往", titleZh: "心之嚮往", slug: "hearts-yearning", image: "/images/gouache/07-hearts-yearning.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-3", image: "/images/gouache/08-untitled-3.jpg", category: "gouache" },
  { title: "阿母的叮嚀", titleZh: "阿母的叮嚀", slug: "mothers-reminder", image: "/images/gouache/09-mothers-reminder.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-4", image: "/images/gouache/10-untitled-4.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-5", image: "/images/gouache/11-untitled-5.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-6", image: "/images/gouache/12-untitled-6.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-7", image: "/images/gouache/13-untitled-7.jpg", category: "gouache" },
  { title: "生命的律動", titleZh: "生命的律動", slug: "rhythm-of-life", image: "/images/gouache/14-rhythm-of-life.jpg", category: "gouache" },
  { title: "花現心靈", titleZh: "花現心靈", slug: "flower-soul", image: "/images/gouache/15-flower-soul.jpg", category: "gouache" },
  { title: "聖潔之花", titleZh: "聖潔之花", slug: "sacred-flower", image: "/images/gouache/16-sacred-flower.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-8", image: "/images/gouache/17-untitled-8.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-9", image: "/images/gouache/18-untitled-9.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-10", image: "/images/gouache/19-untitled-10.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-11", image: "/images/gouache/20-untitled-11.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-12", image: "/images/gouache/21-untitled-12.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-13", image: "/images/gouache/22-untitled-13.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-14", image: "/images/gouache/23-untitled-14.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-15", image: "/images/gouache/24-untitled-15.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-16", image: "/images/gouache/25-untitled-16.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-17", image: "/images/gouache/26-untitled-17.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-18", image: "/images/gouache/27-untitled-18.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-19", image: "/images/gouache/28-untitled-19.jpg", category: "gouache" },
  { title: "花現心靈 NO.6", titleZh: "花現心靈 NO.6", slug: "flower-soul-no6", image: "/images/gouache/29-flower-soul-no6.jpg", category: "gouache" },
  { title: "花現心靈", titleZh: "花現心靈", slug: "flower-soul-var1", image: "/images/gouache/30-flower-soul-var1.jpg", category: "gouache" },
  { title: "白色松鼠", titleZh: "白色松鼠", slug: "white-squirrel", image: "/images/gouache/31-white-squirrel.jpg", category: "gouache" },
  { title: "風中花", titleZh: "風中花", slug: "flower-in-wind", image: "/images/gouache/32-flower-in-wind.jpg", category: "gouache" },
  { title: "MOMA", titleZh: "MOMA", slug: "moma", image: "/images/gouache/33-moma.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-20", image: "/images/gouache/34-untitled-20.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-21", image: "/images/gouache/35-untitled-21.jpg", category: "gouache" },
  { title: "花現心靈", titleZh: "花現心靈", slug: "flower-soul-var2", image: "/images/gouache/36-flower-soul-var2.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-22", image: "/images/gouache/37-untitled-22.jpg", category: "gouache" },
  { title: "歸來", titleZh: "歸來", slug: "return", image: "/images/gouache/38-return.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-23", image: "/images/gouache/39-untitled-23.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-24", image: "/images/gouache/40-untitled-24.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-25", image: "/images/gouache/41-untitled-25.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-26", image: "/images/gouache/42-untitled-26.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-27", image: "/images/gouache/43-untitled-27.jpg", category: "gouache" },
  { title: "Lotes", titleZh: "Lotes", slug: "lotes", image: "/images/gouache/44-lotes.jpg", category: "gouache" },
  { title: "夏日", titleZh: "夏日", slug: "summer-day", image: "/images/gouache/45-summer-day.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-28", image: "/images/gouache/46-untitled-28.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-29", image: "/images/gouache/47-untitled-29.jpg", category: "gouache" },
  { title: "修道者", titleZh: "修道者", slug: "monk", image: "/images/gouache/48-monk.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-30", image: "/images/gouache/49-untitled-30.jpg", category: "gouache" },
  { title: "Swan", titleZh: "天鵝", slug: "swan", image: "/images/gouache/50-swan.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-31", image: "/images/gouache/51-untitled-31.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-32", image: "/images/gouache/52-untitled-32.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-33", image: "/images/gouache/53-untitled-33.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-34", image: "/images/gouache/54-untitled-34.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-35", image: "/images/gouache/55-untitled-35.jpg", category: "gouache" },
  { title: "西班牙風情", titleZh: "西班牙風情", slug: "spanish-charm", image: "/images/gouache/56-spanish-charm.jpg", category: "gouache" },
  { title: "黑面船仔媽", titleZh: "黑面船仔媽", slug: "black-faced-boat", image: "/images/gouache/57-black-faced-boat.jpg", category: "gouache" },
  { title: "半讀", titleZh: "半讀", slug: "half-read", image: "/images/gouache/58-half-read.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-36", image: "/images/gouache/59-untitled-36.jpg", category: "gouache" },
  { title: "月世界", titleZh: "月世界", slug: "moon-world", image: "/images/gouache/60-moon-world.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-37", image: "/images/gouache/61-untitled-37.jpg", category: "gouache" },
  { title: "本質", titleZh: "本質", slug: "essence", image: "/images/gouache/62-essence.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-38", image: "/images/gouache/63-untitled-38.jpg", category: "gouache" },
  { title: "鑽石寶貝", titleZh: "鑽石寶貝", slug: "diamond-treasure", image: "/images/gouache/64-diamond-treasure.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-39", image: "/images/gouache/65-untitled-39.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-40", image: "/images/gouache/66-untitled-40.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-41", image: "/images/gouache/67-untitled-41.jpg", category: "gouache" },
  { title: "想飛的心情", titleZh: "想飛的心情", slug: "want-to-fly", image: "/images/gouache/68-want-to-fly.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-42", image: "/images/gouache/69-untitled-42.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-43", image: "/images/gouache/70-untitled-43.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-44", image: "/images/gouache/71-untitled-44.jpg", category: "gouache" },
  { title: "Untitled", titleZh: "無題", slug: "gouache-untitled-45", image: "/images/gouache/72-untitled-45.jpg", category: "gouache" },
  { title: "Lighthouse of Pictured Rocks", titleZh: "畫岩燈塔", slug: "lighthouse", image: "/images/gouache/73-lighthouse.jpg", category: "gouache" },
  { title: "野百合的春天", titleZh: "野百合的春天", slug: "wild-lily-spring", image: "/images/gouache/74-wild-lily-spring.jpg", category: "gouache" },

  // === Paintings (22) ===
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-1", image: "/images/paintings/01-untitled-1.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-2", image: "/images/paintings/02-untitled-2.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-3", image: "/images/paintings/03-untitled-3.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-4", image: "/images/paintings/04-untitled-4.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-5", image: "/images/paintings/05-untitled-5.jpg", category: "paintings" },
  { title: "George W. Bush", titleZh: "喬治·乔·布希", slug: "george-w-bush", image: "/images/paintings/06-george-w-bush.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-6", image: "/images/paintings/07-untitled-6.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-7", image: "/images/paintings/08-untitled-7.jpg", category: "paintings" },
  { title: "Portrait", titleZh: "肖像", slug: "portrait-1", image: "/images/paintings/09-portrait-1.jpg", category: "paintings" },
  { title: "Portrait", titleZh: "肖像", slug: "portrait-2", image: "/images/paintings/10-portrait-2.jpg", category: "paintings" },
  { title: "Portrait", titleZh: "肖像", slug: "portrait-3", image: "/images/paintings/11-portrait-3.jpg", category: "paintings" },
  { title: "Portrait - Jack", titleZh: "肖像 - Jack", slug: "portrait-jack", image: "/images/paintings/12-portrait-jack.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-8", image: "/images/paintings/13-untitled-8.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-9", image: "/images/paintings/14-untitled-9.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-10", image: "/images/paintings/15-untitled-10.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-11", image: "/images/paintings/16-untitled-11.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-12", image: "/images/paintings/17-untitled-12.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-13", image: "/images/paintings/18-untitled-13.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-14", image: "/images/paintings/19-untitled-14.jpg", category: "paintings" },
  { title: "Portrait", titleZh: "肖像", slug: "portrait-4", image: "/images/paintings/20-portrait-4.jpg", category: "paintings" },
  { title: "Untitled", titleZh: "無題", slug: "painting-untitled-15", image: "/images/paintings/21-untitled-15.jpg", category: "paintings" },
  { title: "浪漫威尼斯", titleZh: "浪漫威尼斯", slug: "romantic-venice", image: "/images/paintings/22-romantic-venice.jpg", category: "paintings" },

  // === Sculptures (10) ===
  { title: "Untitled", titleZh: "無題", slug: "sculpture-untitled-1", image: "/images/sculptures/01-untitled-1.jpg", category: "sculptures" },
  { title: "Untitled", titleZh: "無題", slug: "sculpture-untitled-2", image: "/images/sculptures/02-untitled-2.jpg", category: "sculptures" },
  { title: "Untitled", titleZh: "無題", slug: "sculpture-untitled-3", image: "/images/sculptures/03-untitled-3.jpg", category: "sculptures" },
  { title: "Untitled", titleZh: "無題", slug: "sculpture-untitled-4", image: "/images/sculptures/04-untitled-4.jpg", category: "sculptures" },
  { title: "林博文", titleZh: "林博文", slug: "lin-bowen", image: "/images/sculptures/05-lin-bowen.jpg", category: "sculptures" },
  { title: "陳火木", titleZh: "陳火木", slug: "chen-huomu", image: "/images/sculptures/06-chen-huomu.jpg", category: "sculptures" },
  { title: "Untitled", titleZh: "無題", slug: "sculpture-unknown", image: "/images/sculptures/07-unknown.jpg", category: "sculptures" },
  { title: "李建中", titleZh: "李建中", slug: "li-jianzhong", image: "/images/sculptures/08-li-jianzhong.jpg", category: "sculptures" },
  { title: "陳水扁", titleZh: "陳水扁", slug: "chen-shuibian", image: "/images/sculptures/09-chen-shuibian.jpg", category: "sculptures" },
  { title: "林天扶", titleZh: "林天扶", slug: "lin-tianfu", image: "/images/sculptures/10-lin-tianfu.jpg", category: "sculptures" },

  // === Others (9) ===
  { title: "Hand bag", titleZh: "手提包", slug: "hand-bag", image: "/images/others/01-hand-bag.jpg", category: "others" },
  { title: "Lamp turn", titleZh: "燈飾", slug: "lamp-turn", image: "/images/others/02-lamp-turn.jpg", category: "others" },
  { title: "瓷器繪畫", titleZh: "瓷器繪畫", slug: "ceramic-painting", image: "/images/others/03-ceramic-painting.jpg", category: "others" },
  { title: "琉璃熔合", titleZh: "琉璃熔合", slug: "glass-fusion", image: "/images/others/04-glass-fusion.jpg", category: "others" },
  { title: "飾品", titleZh: "飾品", slug: "accessories", image: "/images/others/05-accessories.jpg", category: "others" },
  { title: "咖啡拉花", titleZh: "咖啡拉花", slug: "latte-art", image: "/images/others/06-latte-art.jpg", category: "others" },
  { title: "Dog outfit", titleZh: "狗服裝", slug: "dog-outfit", image: "/images/others/07-dog-outfit.jpg", category: "others" },
  { title: "Hand made bag", titleZh: "手工包", slug: "handmade-bag", image: "/images/others/08-handmade-bag.jpg", category: "others" },
  { title: "Untitled", titleZh: "無題", slug: "others-untitled", image: "/images/others/09-untitled.jpg", category: "others" },
];

export function getLatestArtwork(): Artwork {
  return artworks[0];
}

export function getArtworksByCategory(category: Artwork["category"]): Artwork[] {
  return artworks.filter((a) => a.category === category);
}

export function getArtworkBySlug(slug: string): Artwork | undefined {
  return artworks.find((a) => a.slug === slug);
}
